version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: restaurant_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: restaurant_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/static:/app/backend/static
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/restaurant_db
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
